#!/usr/bin/env bash
# This script ensures Nginx is installed, configured to listen on port 80, and running.

apt-get update -y && apt-get install -y nginx
sed -i 's/listen [::]:80 default_server;/listen [::]:80;/g' /etc/nginx/sites-available/default
service nginx start
