#!/usr/bin/env bash
# This script listens on port 98 on localhost and prints any received messages.

# Use `nc` (Netcat) to listen on port 98 for incoming connections on localhost.
nc -lk 127.0.0.1 98

