#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-enabled/default
chown -R nginx:nginx /var/lib/nginx
chown -R nginx:nginx /var/log/nginx
systemctl restart nginx

